export const MEMBER_SAVE_STATES = Object.freeze({
  LOCAL_PENDING: 'LOCAL_PENDING',
  SYNCING: 'SYNCING',
  SERVER_CONFIRMED: 'SERVER_CONFIRMED',
  FAILED_RETRYABLE: 'FAILED_RETRYABLE',
  CONFLICT: 'CONFLICT',
})

export const PENDING_MEMBER_SAVE_STATES = new Set([
  MEMBER_SAVE_STATES.LOCAL_PENDING,
  MEMBER_SAVE_STATES.SYNCING,
  MEMBER_SAVE_STATES.FAILED_RETRYABLE,
])

export const isPendingMemberSaveState = (value) => PENDING_MEMBER_SAVE_STATES.has(value)
