import { describe, expect, it } from 'vitest'
import { CSV_BATCH_STATUS, compareCsvBatchEntries, csvBatchEntryFromSession, csvFileBasename, deriveCsvBatchStatus, findNextCsvBatchEntry, getCsvBatchCounts, groupCsvBatchSessions, isCsvBatchFile, isCsvBatchImage, mergeCsvBatchFiles, normalizeCsvBatchBasename } from './csvImportBatch'

const f = (name) => ({ name, size: 1, type: name.endsWith('.csv') ? 'text/csv' : 'image/png' })
describe('CSV batch model', () => {
  it('accepts CSV only', () => expect(isCsvBatchFile(f('Sheet 1.csv'))).toBe(true))
  it('rejects executable files', () => expect(isCsvBatchFile(f('Sheet 1.exe'))).toBe(false))
  it('accepts supported images', () => ['jpg','jpeg','png','webp'].forEach((ext) => expect(isCsvBatchImage(f(`a.${ext}`))).toBe(true)))
  it('removes only the final extension', () => expect(csvFileBasename('Sheet.001.csv')).toBe('Sheet.001'))
  it('normalizes case and whitespace', () => expect(normalizeCsvBatchBasename('  SHEET   2.CSV ')).toBe('sheet 2'))
  it('preserves leading zero display names', () => expect(csvFileBasename('Sheet 001.csv')).toBe('Sheet 001'))
  it('pairs exact basenames across extensions', () => expect(mergeCsvBatchFiles([], { batchId:'b', csvFiles:[f('Sheet 1.csv')], imageFiles:[f('sheet 1.jpg')] })[0].status).toBe(CSV_BATCH_STATUS.READY))
  it('never pairs Sheet 1 with Sheet 10', () => expect(mergeCsvBatchFiles([], { batchId:'b', csvFiles:[f('Sheet 1.csv')], imageFiles:[f('Sheet 10.jpg')] })).toHaveLength(2))
  it('does not fuzzy pair old suffixes', () => expect(mergeCsvBatchFiles([], { batchId:'b', csvFiles:[f('Sheet 2.csv')], imageFiles:[f('Sheet 2 old.jpg')] })).toHaveLength(2))
  it('sorts Sheet 1 through Sheet 10 naturally', () => { const files=Array.from({length:10},(_,i)=>f(`Sheet ${10-i}.csv`)); expect(mergeCsvBatchFiles([], {batchId:'b',csvFiles:files}).map(x=>x.displayBasename)).toEqual(Array.from({length:10},(_,i)=>`Sheet ${i+1}`)) })
  it('puts non-numbered sheets after numbered sheets', () => expect([{displayBasename:'Alpha'},{displayBasename:'Sheet 2'}].sort(compareCsvBatchEntries)[0].displayBasename).toBe('Sheet 2'))
  it('detects duplicate CSV basenames', () => expect(mergeCsvBatchFiles([], {batchId:'b',csvFiles:[f('x.csv'),f('X.CSV') ]})[0].status).toBe(CSV_BATCH_STATUS.DUPLICATE_CSV))
  it('detects multiple images', () => expect(mergeCsvBatchFiles([], {batchId:'b',imageFiles:[f('x.jpg'),f('X.png')]})[0].status).toBe(CSV_BATCH_STATUS.DUPLICATE_IMAGE))
  it('allows missing images', () => expect(deriveCsvBatchStatus({csvFiles:[f('x.csv')],imageFiles:[]})).toBe(CSV_BATCH_STATUS.CSV_ONLY))
  it('allows images first', () => expect(deriveCsvBatchStatus({csvFiles:[],imageFiles:[f('x.jpg')]})).toBe(CSV_BATCH_STATUS.IMAGE_ONLY))
  it('later images pair to existing CSV', () => { const first=mergeCsvBatchFiles([], {batchId:'b',csvFiles:[f('x.csv')]}); expect(mergeCsvBatchFiles(first,{batchId:'b',imageFiles:[f('x.jpg')]})[0].status).toBe(CSV_BATCH_STATUS.READY) })
  it('later CSV pairs to existing image', () => { const first=mergeCsvBatchFiles([], {batchId:'b',imageFiles:[f('x.jpg')]}); expect(mergeCsvBatchFiles(first,{batchId:'b',csvFiles:[f('x.csv')]})[0].status).toBe(CSV_BATCH_STATUS.READY) })
  it('second selection adds instead of replacing', () => { const first=mergeCsvBatchFiles([], {batchId:'b',csvFiles:[f('Sheet 1.csv')]}); expect(mergeCsvBatchFiles(first,{batchId:'b',csvFiles:[f('Sheet 2.csv')]})).toHaveLength(2) })
  it('counts canonical states', () => expect(getCsvBatchCounts(mergeCsvBatchFiles([], {batchId:'b',csvFiles:[f('a.csv')],imageFiles:[f('a.jpg'),f('orphan.jpg')]}))).toMatchObject({csvs:1,images:2,paired:1,missingCsv:1}))
  it('marks invalid entries', () => expect(deriveCsvBatchStatus({csvFiles:[f('x.csv')],imageFiles:[],invalid:true})).toBe(CSV_BATCH_STATUS.INVALID))
  it('marks filename sheet mismatch', () => expect(deriveCsvBatchStatus({csvFiles:[f('x.csv')],imageFiles:[],sheetMismatch:true})).toBe(CSV_BATCH_STATUS.MISMATCH))
  it('preserves saved state', () => expect(deriveCsvBatchStatus({status:CSV_BATCH_STATUS.SAVED,csvFiles:[]})).toBe(CSV_BATCH_STATUS.SAVED))
  it('finds the next sheet', () => expect(findNextCsvBatchEntry([{id:'1',originalCsvFilename:'1.csv'},{id:'2',originalCsvFilename:'2.csv'}],'1').id).toBe('2'))
  it('finds the next unsaved sheet', () => expect(findNextCsvBatchEntry([{id:'1',originalCsvFilename:'1.csv',status:'saved'},{id:'2',originalCsvFilename:'2.csv',status:'ready_for_review'}],'1',{unsavedOnly:true}).id).toBe('2'))
  it('restores a draft entry from history JSON', () => expect(csvBatchEntryFromSession({id:'s',save_result:{batch:{id:'b',displayBasename:'Sheet 1',originalCsvFilename:'Sheet 1.csv'}},source_images:[],import_rows:[],parsed_sheets:[]})).toMatchObject({batchId:'b',sessionId:'s'}))
  it('groups persisted sessions by batch', () => expect(groupCsvBatchSessions([{id:'1',save_result:{batch:{id:'b',displayBasename:'Sheet 1'}},source_images:[]},{id:'2',save_result:{batch:{id:'b',displayBasename:'Sheet 2'}},source_images:[]}])[0].entries).toHaveLength(2))
})
